#- name: Declare variable
#  hosts: all
#  vars:
#    URL: example.com
#  tasks:
#    - name: print the URL variable
#      ansible.builtin.debug:
#        msg: URL - {{ URL }}

- name: Register variable
  hosts: localhost
  connection: local
  tasks:
    - name: shell Command
      ansible.builtin.shell: uptime
      register: output

    - name: Print O/P
      ansible.builtin.debug:
        msg: "{{ output }}"