- name: Demo on loops
  hosts: localhost
  connection: local
  tasks:
    - name : print fruit name
      ansible.builtin.debug:
        msg: Fruit Name - {{ item }}
      loop:
      - apple
      - orange
      - grape
      - banana
    - name: Print fruit name with quantity
      ansible.builtin.debug:
        msg: Fruit Name - {{ item.name }}, Quantity - {{ quantity.name }}
      loop:
        - {name: apple, quantity: 100}
        - {name: orange, quantity: 200}
        - {name: grape, quantity: 300}
        - {name: banana, quantity: 500}