- name: Demo on loops
  hosts: localhost
  connection: local
  tasks:
    - ame : print fruit name
      ansible.builtin.debug:
        msg: Fruit Name - {{ item }}
      loop:
      - apple
      - orange
      - grape
      - banana